//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCprojet.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee1
    {
        public int EmpId { get; set; }
        [Required(ErrorMessage ="Dept Id is Mandatory")]
        public int DeptId { get; set; }
        [Required(ErrorMessage = "Employee Name is Mandatory")]
        public string EmpName { get; set; }
        [Required(ErrorMessage = "Employee Salary is Mandatory")]
        public Nullable<decimal> EmpSalary { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
